#!/bin/sh

set -e

PATH=/sbin:/bin:/usr/sbin:/usr/bin

if [ "$METHOD" = loopback ]; then
	exit 0
fi

(

LOCKFILE=/var/lock/ntpdate-ifup

# Avoid running more than one at a time
if lockfile-create --quiet --retry 0 --lock-name $LOCKFILE; then
	/etc/init.d/S49ntp restart || true
	lockfile-remove --quiet --lock-name $LOCKFILE
fi

) &
