#!/bin/sh
#
# SD card image builder for rpi-buildroot
#
# Guillermo A. Amaral B. <g@maral.me>
#

# sanity check
EUID=`id -u`
if [ ${EUID} -ne 0 ]; then
	echo "${0} requires root privileges in order to work."
	exit 0
fi

section() {
	sync
	echo "*****************************************************************************************"
	echo "> ${*}"
	echo "*****************************************************************************************"
	sleep 1
}

wait_while_busy() {
	while [ "`${LSOF} "$1" 2>/dev/null`" != "" ]; do
		:
	done
}

# overrides
PATH="/usr/local/sbin:/usr/local/bin:/usr/sbin:/usr/bin:/sbin:/bin"
OUTPUT_PREFIX=""

if [ -z "${SIZE}" ]; then
    SIZE="256M"
fi

echo "Creating ${SIZE} size image..."
sleep 3

# dependencies
LSOF=`which lsof`
CP=`which cp`
DD=`which dd`
MOUNT=`which mount`
UMOUNT=`which umount`
MKDIR=`which mkdir`
RMDIR=`which rmdir`
FDISK=`which fdisk`
LOSETUP=`which losetup`
MKFS_EXT4=`which mkfs.ext4`
MKFS_VFAT=`which mkfs.vfat`
TAR=`which tar`

if [ -z "${LSOF}" ] ||
   [ -z "${CP}" ] ||
   [ -z "${DD}" ] ||
   [ -z "${MOUNT}" ] ||
   [ -z "${UMOUNT}" ] ||
   [ -z "${MKDIR}" ] ||
   [ -z "${RMDIR}" ] ||
   [ -z "${FDISK}" ] ||
   [ -z "${LOSETUP}" ] ||
   [ -z "${MKFS_EXT4}" ] ||
   [ -z "${MKFS_VFAT}" ] ||
   [ -z "${TAR}" ]; then
	echo "Missing dependencies:\n"
	echo "LSOF=${LSOF}"
	echo "CP=${CP}"
	echo "DD=${DD}"
	echo "MOUNT=${MOUNT}"
	echo "UMOUNT=${UMOUNT}"
	echo "MKDIR=${MKDIR}"
	echo "RMDIR=${RMDIR}"
	echo "FDISK=${FDISK}"
	echo "LOSETUP=${LOSETUP}"
	echo "MKFS_EXT4=${MKFS_EXT4}"
	echo "MKFS_VFAT=${MKFS_VFAT}"
	echo "TAR=${TAR}"
	exit 1
fi

# sanity check
if [ ! -f "images/rootfs.tar" ]; then
	if [ -f "output/images/rootfs.tar" ]; then
		OUTPUT_PREFIX="output/"
	else
		echo "Didn't find boot and/or rootfs.tar! ABORT."
		exit 1
	fi
fi

IMAGE="${OUTPUT_PREFIX}images/sdcard.img"

# find loop device
LOOP=`${LOSETUP} -f`

# create image
${DD} if=/dev/zero of=${IMAGE} bs=${SIZE} count=1

# partition image
${FDISK} ${IMAGE} <<END
o
n
p
1

+32M
n
p
2


t
1
e
a
1
w
END

${MKDIR} .mnt

# loop image
${LOSETUP} -o 0x100000 --sizelimit 0x2000000 ${LOOP} ${IMAGE} || exit 1

# format boot partition

section "Formatting boot partition..."

${MKFS_VFAT} -F 16 -n BOOT -I ${LOOP} || exit 1

# fill boot

section "Populating boot partition..."

${MOUNT} ${LOOP} .mnt || exit 2
${CP} ${OUTPUT_PREFIX}images/boot/* .mnt
wait_while_busy .mnt
${UMOUNT} .mnt

${SYNC}

# unloop
${LOSETUP} -d ${LOOP}

# loop image
${LOSETUP} -o 0x2100000 --sizelimit 0xDF00000 ${LOOP} ${IMAGE} || exit 1

# format rootfs partition

section "Formatting rootfs partitions..."

${MKFS_EXT4} -L rootfs ${LOOP} || exit 1

# fill rootfs

section "Populating rootfs partition..."

${MOUNT} ${LOOP} .mnt || exit 2
${TAR} -xvpsf ${OUTPUT_PREFIX}images/rootfs.tar -C .mnt
wait_while_busy .mnt
${UMOUNT} .mnt

${SYNC}

# unloop
${LOSETUP} -d ${LOOP}

${RMDIR} .mnt

section "Finished!"

exit 0
